name: 8-1-Thirdparty-API-Authentication-Password-Hasing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Run autograder
        run: node script/grade.cjs

      - name: Upload grading artifacts
        uses: actions/upload-artifact@v6
        with:
          name: 8-1-Thirdparty-API-Authentication-Password-Hasing
          path: |
            artifacts/grade.csv
            artifacts/feedback/README.md
